version: '3.1'

volumes:
  postgres_data:
    driver: local

services:
  db:
    container_name: postgresql_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spotify
    ports:
      - "5432:5432"

  page:
    container_name: next_js
    stdin_open: true
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/music-player-project
      - /music-player-project/node_modules
      - /music-player-project/.next
    ports:
      - "3000:3000"