version: '3.1'

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spotify
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  page:
    container_name: next_js
    stdin_open: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/music-player-project
      - /music-player-project/node_modules
      - /music-player-project/.next
    ports:
      - "3000:3000"